# Generated by Django 4.2.17 on 2025-01-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_profile_rank_alter_profile_bio_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_on',
        ),
    ]
