# Generated by Django 4.2.17 on 2025-01-22 11:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_remove_profile_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='profile'),
        ),
    ]
