# Generated by Django 4.2.17 on 2025-01-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0005_rename_name_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(blank=True),
        ),
    ]
