# Generated by Django 4.2.17 on 2025-01-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(),
        ),
    ]
