# Generated by Django 4.2.17 on 2025-01-16 15:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=cloudinary.models.CloudinaryField(default='empty', max_length=255, verbose_name='image'),
        ),
    ]
