# Generated by Django 4.2.17 on 2025-01-16 16:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_remove_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='file'),
        ),
    ]
